(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



// stage content:
(lib._1to5 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Camada_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAcKkIAAwPIjqAAIAAhdIBGAAQBuAAA9g+QBHhHAHhWIBeAAIAAVHg");
	this.shape.setTransform(136,153.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAbKkIAAwOIjpAAIAAheIBHAAQBtAAA9g/QBHhGAIhWIBdAAIAAVHg");
	this.shape_1.setTransform(136.4,153.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AAmKGIgKizIgFhjIgFhRIAalEIAAhMIgQjJIjwAAIgCgPIAAhQIBGgFQAogCAigKQA7gSAngoQBEhEAOhPIACgNIBdgFIABBOQABAsgDAtIgFBGIgFBGQgEBTAABXIgHBkQgBBkAGBrIAKCSQAIBTAFBXQAEBSAABTIgBAWQhVAHhbAFIAAgEg");
	this.shape_2.setTransform(136.6,153.225);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAxJtIgUifIgLhYQgFgkgDgkIAyk1IAAhCIgfi/Ij4AAIgCgPIAAhSQAggEAkgGQAogEAkgNQA6gUAogqQBFhGAShPIADgNIBcgMQADAjAAAiQABAlgGAoIgKBBQgGAggEAlQgHBTAABcIgQBfQAABVALBgQAIA/ANBIQAPBPAIBYQAKBSgBBXIAAAWQhSAOhbALIAAgEg");
	this.shape_3.setTransform(136.8,152.825);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AA7JUIgeiMIgQhMQgHgggFgfIBMknIAAg2Igvi4IkAAAIgEgNIAAhVQAggGAlgIQAngHAkgPQA7gXApgqQBHhJAVhQIADgNIBdgRQAEAdAAAdQAAAfgIAkIgPA6QgJAggGAlQgLBTAABhIgXBaQAABGAQBUQANA4ATBFQAWBLANBYQANBTAABaIAAAXQhPAVhcAQIAAgDg");
	this.shape_4.setTransform(137,152.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("ABGI6Igoh3IgVhBQgJgcgHgaIBlkYIAAgtIg/itIkHAAIgFgOIAAhXQAfgIAkgLQAngJAlgRQA7gZArgrQBJhLAXhRIAEgNQAxgMArgMQAGAZAAAYQAAAYgLAfIgUA2QgLAdgIAlQgPBUAABlIggBWQAAA3AWBKIAqBwQAeBHASBaQARBUAABdIAAAXQhLAchcAWIgBgEg");
	this.shape_5.setTransform(137.175,152.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("ABQIhIgxhjIgbg3QgMgWgIgWIB+kKIAAgjIhOijIkPAAIgGgNIAAhZQAegKAkgPQAngKAlgTQA9gcAqgtQBMhOAahQIAEgOQAygOAqgPQAHATAAATQAAASgOAaIgZAwQgNAcgLAmQgSBUAABqIgnBRQAAAnAbA/QAWAoAeA+QAmBDAWBaQAWBVAABgIgBAYQhHAjhdAbIgBgDg");
	this.shape_6.setTransform(137.4,151.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("ABbIIIg7hPIgggsQgOgSgKgRICXj7IAAgZIheiaIkWAAIgIgMIAAhcQAdgMAlgSQAmgMAmgWQA9gdAtgvQBMhQAdhRIAFgOQAygRAqgRQAIAOAAANQAAAMgQAVQgNAQgSAbQgQAbgMAmQgXBTAABvIgvBNQAAAXAhA2QAaAfAlA6QAtBAAaBaQAbBWAABjIAAAZQhFAqhdAhIgBgDg");
	this.shape_7.setTransform(137.575,151.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("ABlHvIhFg8IglghQgQgNgMgMICxjtIAAgOIhuiRIkeAAIgJgMIAAheIBBgiQAmgOAngYQA9ghAugwQBOhSAghSIAGgNQAygUApgVQAKAJAAAIQAAAGgTAQQgPAMgVAaQgTAZgOAnQgaBUAAByIg3BJQAAAHAmAsQAfAYArA2QA0A8AfBbQAfBXAABlIgBAaQhBAxhdAmIgCgCg");
	this.shape_8.setTransform(137.775,150.925);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("ABwHWIhPgoIgrgWQgTgIgNgIIDLjeIAAgEIh/iJIkkAAIgLgLIAAhfIBBgnQAlgRAngaQA+gjAvgxQBQhVAjhSIAGgOQAzgWAogYQALAEAAACIgVALQgRAIgYAZQgWAXgQAoQgeBUAAB3Ig9BCQAGAAAkAbQAjAQAxAyQA8A5AjBbQAkBYAABoIgBAbQg+A4heArIgBgBg");
	this.shape_9.setTransform(137.975,150.525);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AB6HAQgrgIgtgMIgwgMQgWgDgPgDIDhjLIiLh+IksAAIgLgJIAAhiIA/gtQAlgSAogcQA+gnAwgxQBShXAmhTIAHgOIANgGQAJgNALgKQAbgXASgEQAZgGAAAGQAAADgMABQgjAXgrAXQgNAQgKAXQgiBUAAB8Ig5AzQAMAAAYALQAoAIA3AxQBDAzAoBdQAnBYAABrIAAAbQg6A/hfAxIgCgBg");
	this.shape_10.setTransform(138.175,149.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AC3D6IiThvIk0AAIgMgJIAAhmQAYgUAmgcQAlgUApgfQA+goAxgzQAyg2Ajg0QAKgtAQglQAUgoAcgVQAegVAUAAQAcgCAAANQAAAIgOAGQgnAeg0AcIgHAOQgQAhgYAiQgLA6AABJIgnAdIAPACQAsABA9AsQBLAxAsBcQAsBaAABuIAAAcQg3BGhfA2IgCgBQgwACgzgCIg1AAIgpADg");
	this.shape_11.setTransform(138.375,148.592);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AC+ETIiZhgIk7AAIgOgJIAAhoQAXgWAnggQAkgVAqghQA/grAxg0QAmgpAdgmQAJhVAdg8QAWgpAfgTQAhgUAWADQAeAEABATQAAANgPALQgnAhg0AfIgIAOQgYAvgnAyQgDAiAAAmIAAAAQAnADAzAfQBSAuAwBcQAxBbAABxIgBAcQgzBNhfA8IgCAAQg1AMg4AIIg7AKQgaAGgTAGg");
	this.shape_12.setTransform(138.55,149.13);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("ADBEvIibhTIlDAAIgPgIIAAhpQAWgYAngjQAkgZAqgiQBAguAyg1IARgSIg3AdQAAhHBBgJQAOgEAOAAQAFhyAnhKQAZgqAggQQAlgSAYAGQAhAJAAAZQAAASgRAQQglAkg1AiIgIAOQgdAzgrA3QAoACAxAZQBaApA1BeQA1BbAAB0IgBAdQgcAxgtArIAAAOIgJgFQgcAZgiAXIgCABQg5AVg9ASIhBAVQgYAJgSAJg");
	this.shape_13.setTransform(138.775,149.4513);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AghGlIBFggQBCgcA/gfIACgCIAKgHIiKg9IlKAAIgRgIIAAhsQAVgaAogmQAjgbAqgkQBBgwAzg3QBBhGAthAQghgJgcADQAIheAlg/QAagqAjgPQAogRAaAKQAkAOAAAfQAAAYgSAVQglAng1AlIgJAOQgOAXgQAYQATAFAVAJQBiAmA5BfQA6BbAAB3IgBAeQgqBWhZBEIAPAGIkWB9QAVgQAggPgADAFHIA0gXIAAAvgAgnjZQAQgHASgCQgDAhgBAlIhlAtQAAhWBHgUg");
	this.shape_14.setTransform(138.95,150.0863);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgmGiIBLgrQAqgWApgXIhRgeIlRAAIgSgGIAAhvQAUgcAogpQAjgdAsgnQBAgyA1g4QBahiA2hWIAGgJIgCgBQg7gVguAIQAMhLAgg0QAcgqAmgOQArgPAdAOQAmATgBAlQABAdgUAaQgkAqg2AoIgDAFQBoAiA9BfQA9BdABB5IgBAfQgqBihgBLIgDACIg3AiIBAAYIkXBpQAXgVAigUgAC4FiIBNgcIAAA4gAg6j+QATgJAWgEQgIAwAAA5IhtApQAAhmBMgfg");
	this.shape_15.setTransform(139.15,150.5371);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgqGgIBQg2IAXgOIgVgGIlYAAIgTgGIAAhxQASgeAogsIBPhIQBBg2A1g4QBdhlA5hWIAKgPQAbgVAWgWQBGAjAvBFQBCBeAAB8IAAAfQgmBphhBRIgEACQg8AshAApIBsAhIkRBVQAagZAkgZgACpF9IBsghIAABDgAhNkiQAYgOAbgFQAOg3AZgoQAfgrApgMQAtgNAfASQApAXAAAsQAAAigUAfQgSAWgXAWQgdgOgggJQg7gSgvAKQgQA9AABRIh1AkQABh2BRgpg");
	this.shape_16.setTransform(139.35,150.948);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgvGeIApgfIAvAAIBlAZIj/BBQAbgeAngdgACOGYICYgmIAABNgACOGYgAk3F/IgUgFIAAh0QARggApgvIBOhMQBDg4A2g5QBfhoA7hWIAKgPQA3gtAigwQAvAfAjAwQBHBfAACAIAAAfQgjBwhiBWIgDADQhMA+hSA5IgsAigAhglGQAegUAkgHQAMgiASgbQAhgrAsgLQAwgLAhAVQArAcAAAyQABAngXAlIAAAAQgwgfg8gNQg4gOgtAJQgdBKAABqIh8AgQAAiFBXg0g");
	this.shape_17.setTransform(139.55,151.3215);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AhDGoIBtAAIA2ALIjaAtQAYgcAfgcgABgGzIDXgrIAABXgABgGzgAk9GoIgWgEIAAh2QAQgiAqgxQAhgkAtgtQBDg7A2g7QBhhpA/hXIALgPQA3gwAigzQAPgaAFgcQAmAbAdAmQBLBgAACDIgBAgQgfB2hiBcIgEAEQhQBIhXBCIhcBMIgOAMgAhzlpQAngdAwgIQgvBTAACJIiFAbQAAiUBdg+gADGlUQg6gphOgOQgxgKgpAHQAIgNAJgMQAhgsAvgJQAzgKAjAZQAuAhAAA4QAAAQgDAQIAAAAg");
	this.shape_18.setTransform(139.75,151.6821);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AArHGIgmAAIiHAWIASgWIB1AAIFCg0IAABigAlEHGIgXgDIAAh5QAPgkAqg0QAhglAugwQBDg+A4g8QBjhrBBhYIAMgPQA3gzAhg2QAZguAAgyQAAgNgCgLQAnAaAeAlQBQBhAACGIgBAhQgbB9hjBiIgEADQhVBThcBMIhhBWQgfAcgYAcgAiGmZQA1gpBDgHIgKAMQhDBWAACkIiNAXQAAikBihJgAA2nGQgkgFggACQAhghAqgHQA2gIAlAdQAnAeAIAuQg+gqhTgMg");
	this.shape_19.setTransform(139.925,153.2287);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AAsHjIl2AAIgZgCIAAh7QAOgmAqg4QAhgnAugyQBEhAA5g+QBlhtBEhYIAMgQQA4g1Agg5QAag0AAg3QAAg+gqgpQBCAdAwA4QBTBiAACIIgBAiQgXCEhkBnIgEAEQhaBdhhBWIhmBhQguAsggArIHkg7IAABsgAiZnJQBPhCBsAJQgnAKghAlQhGBWAACpIiVASQAAi0BohTgAAuoBIgMgBIASgEQA6gGAnAgIAJAIQgzgWg9gHgAAioCIAAAAg");
	this.shape_20.setTransform(140.15,154.8201);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAtISIl+AAIgZgCIAAh9QAMgoArg7QAggpAvg0QBEhDA6g/QBnhvBHhZIANgPQA4g5Agg8QAbg4AAg9QAAhKg2gwQgpgkg9AFQg1AEgpAuQhLBVAACuIicAOQAAjEBthdQBYhOB5AKQCWALBYBkQBYBjAACLIAAAjQgVCMhjBrIgFAFQhfBmhmBgIhrBsQgwAwgiAxIH8gsIAAB1g");
	this.shape_21.setTransform(140.325,154.6877);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AArJCImggBIAAiAQALgqArg9QAggrAwg2QBEhGA7hAQBqhzBJhZIAOgPQA4g7Afg/QAdg+AAhBQAAhRg5g1QgrgohAAEQg4ADgrAuQhOBWAACyIikAJQAAjTByhoQBdhWB/AHQCdAHBdBlQBcBjAACPIgBAjQgRCThkBxIgEAFQhkBwhrBqIhxB3QgyA1gkA1IIWgeIAACBg");
	this.shape_22.setTransform(140.825,154.3737);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AAnJzImogBIAAiCQAKgsArhAQAggtAwg5QBFhIA8hBQBrh1BNhZIAOgQQA5g+AehCQAehCAAhHQAAhXg8g6QgtgrhDABQg6ACgtAuQhTBWAAC3IirAFQAAjjB3hzQBhhdCGADQCkAEBhBlQBhBkAACSIAAAkQgOCahkB2IgFAFQhpB7hwBzIh2CCQg1A6glA6IIvgPIAACKg");
	this.shape_23.setTransform(141.475,154.0437);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AmOKkIAAiFQAQhOB2iNQDCjTB8iLQCFiNAAicQAAheg+g+QgvgvhGAAQg9AAgwAvQhVBWAAC7Ii0AAQAAjyB9h9QBlhmCMAAQCsAABmBmQBlBlAACVQAAC7h1CMQhuCFh0B9Ih8CMQg4A/gmA+IJJAAIAACVg");
	this.shape_24.setTransform(142.1,153.675);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("Ai8KXIjRgHIAAhIIAAg9QAPg6BKhdIAggnIAOgRIBthtIBjhkQA+hBAzg3IAGgGQBLhSAdhZQAUg8gBg9QgBgggIgcQgPg3gpgnQgRgQgTgKQgbgPghgEIgVgCQg0gCgpAhIgKAKQgKAKgJAMQgjA0gNBNQgHAvAAA5IhMgDIhggEQgBgoADgkQAEhGAPg5QAShCAkgwQAOgTARgRQA4g3BHgTQAugRA1AAQAZAAAZADQCAAIBTBNQAcAaAVAdQA2BMAEBmQABAkgCAiQgMCIhVBwIgHAKQhPBmhXBmIgoAtQg7BJg/BFIgBABQguA0gkAyIgLAUIB/ADQCFAECBAGICzAIIgDBzIgBAgQiPAEiSAAQiTAAiSgFg");
	this.shape_25.setTransform(142.225,154.525);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("Ai/KKQhpgGhjgIIgBhJIAAg9QATg3BKhZIAfgjIANgPQA2gyA2gwIBkhdQA/g+Azg4IAGgGQBLhQAchcQATg8gCg9QgBgfgJgdQgQg1gqgnQgRgQgUgJQgbgOghgEIgUgCQgxgFgoAdIgJAKIgQAVQgfAygJBGQgGAsACA0IhJgHIhdgIIAAhLQAChFALg3QAOg/AggsQANgRAQgPQA0gyBDgOQAqgQAwAAQAXAAAWADQB6ACBTBEQAcAYAVAbQA3BFAIBhQADAhgBAhQgDCDhOBuIgGAKQhIBmhTBpIgmAuQg7BJg9BGIgBABQguA0glAxIgKATQBAABA+AEQCDAIB8ANQBWAJBTAGQgCA6gEA5IgCAgQiNAHiTAAQiUAAiQgKg");
	this.shape_26.setTransform(142.325,155.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AjDJ+QhogKhggNIAAhIIAAg9QAVg1BMhVIAdgfIANgNQA0gtA1gqQA1gqAxgsQBBg7A0g5IAGgGQBJhPAchdQASg9gEg8QgBgggKgbQgRg2grglQgRgPgUgJQgbgOgggDIgTgEQgvgHgnAZIgIAKQgHAJgGALQgbAvgGBBQgDAoACAvIhGgKQgqgHgvgGIgChLQgBhEAIgzQAKg9AcgnQALgQAPgNQAxgtA/gJQAmgPAqAAQAWAAAUADQB0gFBSA+QAbAUAWAZQA4A/AMBbQAEAgACAfQADB8hFBuIgFAKQhBBmhPBrIgkAuQg5BMg9BFIgBABQgvA0gmAuIgJATQBAADA/AGQCAALB3AUQBSANBNAKQgDA5gGA5IgDAfQiMALiUAAQiUAAiPgOg");
	this.shape_27.setTransform(142.45,156.275);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AjHJyQhmgOhcgRIgBhIIAAg9QAZgzBMhRIAcgbIAMgLQAxgmA3glQA0gmAzgqQBCg5A0g4IAGgGQBKhOAZhfQARg9gDg8QgDgggKgbQgTg1grgkQgRgPgUgJQgbgMgigEIgRgEQgtgJgkAVIgHAJQgGAJgGAKQgVAtgDA7QgBAkACAqIhCgOQgpgJgsgHIgFhLQgChDACgxQAHg6AZgiQAKgPAMgLQAtgoA8gEQAhgOAmAAQAUAAARADQBugLBSA2QAbASAWAWQA5A4AQBWQAGAeADAdQALB3g8BtIgGAKQg4BnhMBrIgjAwQg2BNg+BFIgBABIhWBhIgHASQBAAEA9AHQB/AQBxAaQBOARBIAOQgFA5gHA4IgDAeQiLAPiVAAQiVAAiOgSg");
	this.shape_28.setTransform(142.55,157.125);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AjKJmQhlgRhZgVQgBgkAAgkIAAg9QAcgwBMhNIAbgXIAMgKQAvggA3ggQA0ghA1goQBDg2A1g4IAGgGQBJhNAYhhQARg+gGg8QgDgfgLgbQgUg0grgjQgSgPgTgIQgcgMghgDIgQgGQgrgLgjARIgGAJQgFAIgEAKQgSArABA1QABAgADAlQgegIgfgJQgogMgrgJIgGhKQgFhCgCgvQADg2AVgeQAIgNAMgKQApgiA5ABQAcgOAiAAQARAAAPADQBpgRBQAuQAbAPAXAUQA5AxAUBRQAIAcAFAcQATBxg1BsIgFAKQgxBmhHBuQgRAZgRAXQg0BPg+BFIgBABQgvA0goArIgFARQA/AFA8AKQB+AUBrAgQBKAWBCARQgFA5gJA3IgFAeQiJASiXAAQiVAAiMgXg");
	this.shape_29.setTransform(142.65,157.8706);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AjNJcQhlgUhVgaQgBgkAAglIAAg9QAfgtBNhJIAagTIALgHQAtgaA3gcQA0gcA2gmQBGgzA1g4IAFgGQBJhMAXhjQAQg+gHg8QgEgfgLgbQgVgzgsgjQgSgNgTgIQgcgLgigDIgPgHQgogOgiAOIgDAIIgIASQgNAoAEAvIAGA8QgcgJgegMQglgNgqgLIgIhKIgMhtQgBg0AQgaQAHgLALgHQAkgeA2AGQAYgNAdAAQAPAAANADQBigXBQAmQAbANAWARQA6ArAaBLQAJAbAGAaQAbBrgtBsIgEAJQgqBmhEBwQgPAZgQAYQgzBRg+BEIgBABQguA0gqApIgEARQBAAGA7AMQB8AXBmAnQBGAaA8AUQgGA5gLA3IgFAdQiIAWiXAAQiXAAiKgbg");
	this.shape_30.setTransform(142.75,158.5449);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AjRJSQhjgYhSgeQgCgkAAgkIAAg9QAjgrBOhFIAYgPIAKgGQAsgTA3gXQA1gYA3gjQBGgwA2g5IAGgGQBIhLAVhlQAPg/gHg7QgFgegLgbQgXgzgsghQgSgOgUgHQgdgLgggCIgOgIQgngQgfAKIgDAHQgEAIgCAJQgIAmAHApIAJAzQgagKgcgOQgjgQgpgMQgEgngGgjQgJhAgKgpQgFgxANgVQAFgKAJgFQAhgZAzALQATgMAZAAQAMAAAKACQBegdBPAfQAaAKAXAOQA7AlAeBGQAKAYAIAZQAjBlglBrIgDAKQgiBlhABzQgPAZgQAYQgwBSg+BEIgBABQgvA1grAnIgCAQQBAAHA5AOQB8AbBfAuQBDAeA3AYQgIA4gNA2IgHAdQiFAaiZAAQiXAAiJggg");
	this.shape_31.setTransform(142.875,159.1058);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AjUJKQhigchOgiQgDgkAAgkIAAg+QAmgoBPhBIAWgKIAKgFIBhgeQA1gUA4ghQBIgtA3g5IAGgGQBHhLAUhmQAOg/gJg7QgEgegNgbQgYgzgsgfQgSgNgVgHQgcgKghgDIgNgIQglgTgdAHIgCAHQgCAHgBAIQgEAkALAjQAGAVAFAVIgygbQghgSgngPQgGgngHgiQgLg/gOgnQgIguAIgRQAEgHAIgEQAdgUAvAQQAPgLAUAAQAJAAAJACQBXgjBPAXQAaAIAXALQA8AeAiBBQAMAXAKAXQAqBfgdBqIgCAKQgbBkg8B3QgOAZgPAYQguBUg+BDIgBABQgvA1gtAlIAAAQQA/AIA6APQB5AgBaA0IBwA9QgJA5gOA1IgIAdQiEAdiaAAQiYAAiHgkg");
	this.shape_32.setTransform(142.975,159.5979);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AjYJBQhhgehLgnQgCgkAAglIAAg9QApgmBPg9IAWgGIAJgDQAngHA4gMQA1gPA6gfQBJgqA3g5IAGgGQAMgNALgNQgeAtgkAnIgBABQgxA1gtAjIABAQQA/AJA6ARQB3AjBVA7IBmBFQgKA4gQA1IgJAcQiDAhibAAQiZAAiFgpgACkACIADgGQAQglAIgpQANhAgKg6QgGgegNgaQgYgzgugfQgSgMgUgGQgdgKghgCIgMgKQgigUgbACIgBAHIgCAOQACAiANAdQAIARAGAQIgugeQgggVglgQQgGgngJgiQgNg+gSgkQgNgsAFgMQADgGAGgCQAZgPAtAWQAKgLAOAAQAIAAAGACQBTgqBNAQQAaAFAXAJQA9AYAmA7QAOAVALAWQAyBZgVBpIgCAKQgSBkg5B5QgLAXgNAVQgRAngaAjQAVghATgjg");
	this.shape_33.setTransform(143.1,160.0161);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AjcI6QhggihGgrQgDgjAAglIAAg+QAsgjBQg5IAUgCIAJgBQAlgBA5gHQA1gKA6gdQAXgMATgNQAfgaAggjIABgBQA9hCAqhWIALgVQgVBbg/BCIgFAGQgoAogxAgQgQAOgQAMIACAPQA/AKA5ATQB2AnBOBBQA3AsAmAhQgKA4gTA0IgKAcQiAAlidAAQiZAAiFgugADBhBQANhAgLg6QgGgegOgaQgagygugdQgSgMgVgGQgdgJgggCIgLgLQghgWgZgCIAAAGIABAOQAGAfARAXQAKAOAHALIgrgiQgdgXglgSQgGgngKghQgQg9gWgjQgQgoABgIQAAgEAGAAQAVgKAoAbQAGgKAKAAQAFAAAEACQBNgwBMAIQAaACAZAHQA9AQAqA3QAPATAOAUQA5BTgNBpIgBAJQgLBkg1B7IgPAfIAEgWg");
	this.shape_34.setTransform(143.2,160.3429);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AjfI0QhfglhDgvQgDgkAAglIAAg9QAvghBRg1QAIACAKgBIAJACQAiAFA5gCQA1gGA9gbQAVgKATgMIgOgDIgEgOQAvggAxg2IABgBQA+hCAohXIAEgJIgBAIQgRBshFBJIgGAGQgoAog0AfQA3ALAxASQB1ArBJBIQAzAvAgAmQgMA3gUA0QgFAOgGANQh/AoieAAQiaAAiCgygADDioQgGgfgOgaQgcgwgugdQgTgMgVgFQgdgIgggCIgLgMQgdgZgYgFIABAGIADANQAFAOAIALIgCgBQgbgZgjgUQgHgngMghQgSg8gZggQgUgmgEgCQAAgBAAgBQABAAAAAAQABgBAAABQABAAABAAQARgEAmAgQABgKAFAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQBIg2BLAAQAaAAAYAEQA/AKAuAxQARARAPAUQBBBNgFBnIAAAJQgEBkgxB9QgJAXgLAVQAKg8gMg1gAgdkzQgKgIgIgMIAlAkIgTgQg");
	this.shape_35.setTransform(143.325,160.5498);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AjjIwQhdgphAg0QgDgjgBglIAAg+ICFhPQAHAEAKACIAIACQAgAMA6ADQA1gBA9gZQAzgXAqgfQAiAJAfAOQBzAvBDBOQAwA0AbAoQgOA4gVAyIgNAcQh9ArifAAQibAAiBg2gAAOC5IgGgOQAxgeAyg2IABgBQA6g9AkhRIgEAdQgPBthFBIIgGAGQgTAUgWARQgagHgbgFgADEiVQgHgegPgZQgdgxgugbQgTgLgVgGQgegHgfgCIgKgMIgQgPIAiAoQgHgBgOgGQgYgLgPgbIgFgLIgDgGQAPAGASAPQgZgbgigWQgIgmgNghQgUg7gdgeQgPgVgJgIQAPAHAaAdIgDgIQBDg8BKgHQAYgDAZACQBAADAyAsQASAPARASQBJBHADBnIABAJQADBjgtCAQgKAcgNAZIgFANQAEgxgKgsgAiQohIAAABIgBABIABgCgAiQoggAi9o+QAAgBgBAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQADgBAFAFIgHgCg");
	this.shape_36.setTransform(143.45,160.6469);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AjmItQhdgtg8g3QgEgkAAglIAAg+QA3gbBSgtIAPAKIAHAEQAfASA6AHQA1AEA/gXQBOgeA4g3QgmgOgqgIIgHgOQAygcAyg1IABgBQAwg0AhhCQAAgogJglQgIgegPgYQgegxgvgaQgTgLgWgEQgdgHgfgCIgKgNIgBgCQAGACAHACQAQACAIgDQgOgVgRgYQgXgegggXQgJgmgOghQgWg5gggbQA0gxA/gNQAZgFAYgBQBBgDA3AnQATANATAQQBQBCALBlIACAKQALBigqCCQgJAcgMAaQgHAUgJATQgBAWgDAXQgOBvhFBIIgGAGIgCACQATAHATAJQBwAzA+BUQArA4AWAsQgOA4gYAyIgNAbQh8AvigAAQicAAh/g7gAgwlBIgIgLIgDgFQATANAZAcQgTgHgOgSgAicoPIgFABIAHgIQgWgdgIgEQgBgFADgBQALgFAcAfIACABIgNAMIAKAOQgHgHgFAAgAiNoiIAAAAg");
	this.shape_37.setTransform(143.525,160.5424);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AjpIqQhcgvg5g8QgEgkAAglIAAg+QA5gZBTgpIAPAOIAGAGQAdAYA5ANQA2AIBAgVQBRgcA6g4IAFgGQANgNAKgOQgugUg0gMIgJgNQAzgaAzg1IABgBQAmgoAbgyQgBghgIgfQgJgegQgYQgfgwgvgZQgUgKgVgFQgegGgfgCIgJgOQgQgWgOgPIADADQAZAWAdgBQASgCAJgIQgMgWgQgaQgUgggfgZQgKgngPggQgYg5gmgYIgGgFQAngiAugPQAYgHAZgEQBCgJA6AhQAVALAVAPQBYA8ATBkIACAKQATBigmCEQgJAdgKAaQgNAkgRAgQABAcgEAdQgKBegwBAIATAJQBvA3A4BbQAnA9AQAvQgPA3gaAyIgNAaQh7AziiAAQicAAh9hAgAg0k6IgBgBIAHAIIgGgHgAion9IgKABIAQgUIgSggQABgHADgCQAOgJAcAXQgOAMgOAPIAPAaQgMgHgJAAgAiGorIAAAAg");
	this.shape_38.setTransform(143.65,160.3536);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AjtIpQhagzg2hAQgEgkAAglIAAg+QA9gWBUglIAMASIAGAIQAbAeA6ASQA2ANBCgTQBSgZA5g5IAGgGQAbgcASgjQgygZg6gOIgKgNQA0gYAzg2IABgBQAcgdAVgiQgCgagHgYQgJgdgRgYQghgwgvgYQgUgKgWgDQgdgGgfgCIgIgPQgVgigQgUIAFAEIAMAJQAcAUAhgIQAVgFAJgOQgJgXgQgcQgSgjgdgaQgKgngQgfQgbg4gqgWQgJgHgIgEQAbgWAfgNQAYgKAagHQBCgPA/AbQAWAKAXANQBfA2AbBkIAEAJQAZBighCHQgJAdgJAaQgSA0gaAsQAEAhgFAmQgHBGgbA1IAIAEQBtA7AzBiQAjBBAKAyQgQA3gbAxIgQAaQh4A2ijAAQidAAh8hEgAi0nqIgPABQANgUAOgRQgGgRgCgIQACgJAGgEQAOgLAYAMQgUAQgSAVIASArQgQgHgOAAg");
	this.shape_39.setTransform(143.75,160.0706);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AjwIpQhag2gyhFQgEgkAAglIAAg+QBAgUBUghIALAWIAGAKQAYAlA7AWQA2ASBDgRQBUgXA5g4IAGgGQApgqAUg8IADACQBsA/AtBoQAfBFAFA2QgRA3gdAwIgQAaQh3A6ilAAQidAAh6hJgABRBmIgLgMQA1gWAzg2IABgBQASgRAOgVQgDgRgFgRQgKgdgRgYQghgvgwgXQgVgJgWgEQgdgFgfgBIgHgQQgTgkgOgZIAGAEIAOAIQAhASAkgOQAXgJAKgTQgIgZgNgeQgQgkgdgdQgJgmgTgfQgdg3gtgUQgUgMgQAAQASgPAVgLQAYgNAagJQBDgWBDAXQAYAHAYAMQBnAwAkBjIADAJQAhBigeCJQgHAdgJAbQgVBFgmA1QAHAogFAvQgEAugMAnQgzgdg9gQgAjAnWIgUABQASgiAXgbQADAWAQAsQgVgGgTAAgAiroeQADgLAHgFQALgKAQACQgUAPgRAVIAAgMgAiGo2IAAAAg");
	this.shape_40.setTransform(143.875,159.7187);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("Aj0IqQhYg6guhJQgFgkAAglIAAg+QBDgSBVgcIAKAaIAFALQAWArA7AbQA2AXBEgPQBWgUA6g4IAGgGQA2g3AQhaQgxgeg8gQIgNgLQA2gVA0g1IABgBIANgOQAMAvgFA4QgBAWgEAVIAGAEQBpBCAoBvQAbBJgBA6QgSA2gfAwIgRAZQh1A+imAAQieAAh5hNgADIgiQgKgdgSgYQgjgvgwgVQgVgJgWgDQgegEgfgCIgGgQIgdhDIAIADIAQAHQAlAPAogTQAYgNALgYQgFgagMggQgOgngcgeQgLgmgSgfQggg2gxgSQgsgUgbAYQgIAHgFAMQgFAaARA+QgZgEgYAAIgYAAQAmhbBIguQAYgPAagMQBEgdBHASQAZAGAaAKQBvAqAsBiIAEAJQApBhgbCMQgGAdgIAbQgYBYg0A9IgFgSg");
	this.shape_41.setTransform(143.9768,159.2707);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("Aj4IrQhYg9gqhNQgFgkAAglIAAg+QBGgPBWgZIAIAeIAFANQAUAxA7AhQA2AbBGgNQBXgRA7g4IAGgGQBBhEAIh5IABgDQgugcg3gPIgPgLQA0gSAxguQATA0gEBCIANAJQBoBHAiB1QAXBOgGA9QgUA2ggAvIgSAZQh0BBinAAQifAAh3hSgACrg9QglgugwgUQgVgJgWgCQgegEgfgBIgGgSIgYhIIAJACIASAGQApANArgaQAbgQALgdQgDgcgKghQgMgqgaggQgMgmgVgeQghg1g1gPQgwgRgfAcQgKAIgFAPQgKAeAOBEQgegEgcAAIgdAAQAhhhBHg1QAXgSAbgPQBGgjBKAMQAbAEAcAJQB2AkA0BhIAFAJQAwBhgWCOQgFAegIAbQgZBkg+BAIgBABIgHAIQgLgdgSgYg");
	this.shape_42.setTransform(144.1704,158.7484);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("Aj9IsQhXhAgmhRQgGgkAAgmIAAg+QBKgNBWgUIAHAiIAEAPQASA3A8AmQA2AgBHgLQBZgOA7g5IAGgFQBBhDAGh7QACgbgCgZQAOAIANAKQBnBKAcB8QATBSgMBAQgUA2gjAuIgTAZQhyBFioAAQifAAh2hXgACBAyIgQgLQAogMAlgdQgJgSgMgPQgmgtgxgUQgVgIgWgCQgfgDgeAAIgFgUIgUhOIAKACIAUAFQAuALAuggQAdgUAMgiQgBgegJgjQgKgrgZgjQgMglgWgfQgkg0g5gMQgzgOgjAgQgLALgIAQQgNAjALBJQgigDghgBIgiABQAbhnBGg9QAYgVAbgRQBGgqBPAHQAcACAeAHQB+AeA8BhIAFAJQA4BggTCRQgEAdgHAcQgXBmg9BAIgBABQgQAQgRANIAJASQANAhADAmQgngYgvgNg");
	this.shape_43.setTransform(144.4286,158.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AkDIvQhVhEgkhVQgGgkAAgmIAAg+QBNgKBYgQIAFAmIADAQQAQA+A8AqQA3AlBIgJQBagLA8g4IAGgGQBAhCAGh+QADg8gQgwQAcAPAZAUQBlBOAWCCQAQBXgSBDQgVA2glAuIgUAYQhxBIipAAQigAAh0hbgACQAhIgSgKQAZgGAYgOIgJgKQgngugygSQgVgHgWgCQgfgCgegBIgEgUIgRhUIAMABIAWAEQAzAJAxgmQAfgYAMgnQABgfgGglQgJgugXgkQgNglgXgfQgngzg8gJQg3gMgnAlQgNAMgJASQgRApAIBOQgngDgmAAIgmAAQAWhtBFhFQAXgXAbgUQBIgwBTABQAdABAgAGQCGAXBDBgIAHAJQA/BggPCTQgDAegHAcQgVBog9A/IgBABQgeAfggARQANASAJAWIAGAOQgcgOgfgKg");
	this.shape_44.setTransform(144.764,157.5478);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AkJIyQhVhHgfhaQgHgkAAglIAAg/QBRgHBYgMIAEAqIACASQAOBEA9AvQA2ApBKgGQBbgIA8g5IAGgGQBBhBADh/QADhFgXg1QgMgdgVgWIAAgBQA8AVAvAnQBjBSARCJQAMBbgYBGQgWA2gmAtQgKANgLALQhwBMiqAAQihAAhyhggACeASIgTgKIAKgDQgjgggqgOQgVgHgXgBQgdgCgggBIgDgVIgMhaIAMABIAZADQA3AHA1gtQAhgbANgsQADghgFgnQgHgwgWgmQgNglgZgeQgogyhBgHQg7gJgrApQgOAOgKAUQgVAtAEBUQgrgDgrAAIgrABQAQh0BFhNQAXgZAcgWQBIg3BYgEQAegCAhAFQCOASBMBfIAHAJQBHBfgMCVQgCAfgGAcQgTBpg9A/IgBABQgxAyg1AOIANAOIgEgBg");
	this.shape_45.setTransform(145.1778,156.8313);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AkRI2QhThLgcheQgHgkAAglIAAg/QBUgFBYgIIADAuIACAUQAMBKA9A1QA3AtBLgEQBcgGA9g4IAGgGQBAhAACiBQAChGgYg0QgNgdgVgWQgpgtgzgOQgVgHgXgBIg+gBIgBgWIgJhhIAOABIAaACQA9AEA4gyQAigfAOgxQAFgigEgpQgEgzgUgnQgPgmgagdQgqgxhFgFQg/gGgvAuQgPAPgMAWQgYAzABBYIhggBIgwAAQALh6BEhUQAWgdAdgYQBJg+BcgJQAggDAjADQCVALBUBfIAHAJQBPBfgICXQgBAggFAcQgRBrg9A+IgBABQg2A3g8ALIAUAIQBAAWAvAqQBhBXAMCPQAIBfgdBKQgYA2goAsIgWAXQhuBQirAAQiiAAhxhkg");
	this.shape_46.setTransform(145.6615,156.075);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AkYI6QhShOgZhjQgHgjAAgmIAAg/ICwgGIACAyIABAWQAJBQA+A5QA3AzBNgCQBegDA9g5IAGgGQA/g/ABiDQABhGgZg0QgOgcgVgXQgrgrgzgPQgVgGgYgBIg9AAIgBgWIgEhnIAOABIAdABQBBACA7g5QAlgiAOg3QAHgjgCgrQgCg1gTgpQgPglgcgeQgsgwhJgCQhDgDgyAyQgSARgMAYQgdA3gCBeIhpgBIg1AAQAGiABDhcQAWgfAdgbQBKhEBhgOQAigGAjACQCdAGBcBdIAIAJQBWBfgDCZQgBAggFAdQgOBsg9A/IgBABQg2A2g+AKQAMAEAKAFQA/AWAvAsQBgBaAFCVQAEBkgiBNQgZA2gqAsQgLAMgMAKQhsBUirAAQikAAhvhpg");
	this.shape_47.setTransform(146.1708,155.2839);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AkgI+QhuhtABiUIAAg/IC0AAIAAA3QgBBlBHBHQA3A2BNAAQBlAAA/g+QA+g/AAiFQAAhtg+g/Qg/g+hOAAIg9AAIAAiDIAuAAQBGAAA+g/QA/g+AAh2QAAhlg/g/QgvgvhOAAQhGAAg2A3Qg+A/gJCMIirAAQAAizB1h2QBlhlCUAAQCsAABlBlQBeBeAACcQAACdhOBOQg3A2g+AIQBOAYA3A1QBdBeAACcQAACshtBtQhtBujDAAQijAAhuhug");
	this.shape_48.setTransform(146.75,154.45);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AkcIxQgsgqgbgxQglhJAAhYIAAg9ICvgFIABAzQABBJAoA3QAOAVASASQA2A0BLgBQBgAAA9g9QA1g2AHhpQACgVAAgYQAChrg7g+Qg6g+hKgCIg6gBIACiBIAtAAQBGAAA+g8QAMgMAKgNQAbg1ABhMQAAhjg7g8QgtguhKgBIgPABQg5AFguAuQgzAzgNBrQgCARAAASIilACQAAiqBwhvQBihgCNACQClABBhBjQAqArAXA4QAZA/AABRQAACXhLBMQg0A1g8AJQAWAGAUAKQAwAWAlAlQBMBOAMB6QACASgBATIABATQAACRhWBhIgUAUQhuBpi+AAQihAAhuhpg");
	this.shape_49.setTransform(146.075,154.7488);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AkXIkQgsgpgcguQgjhJAAhWIAAg9ICqgIIABAvQADBCAmAzQANAQARAPQA0AvBKgDQBfgFA7g9QAxgyAMhbQACgXABgZQAChpg2g+Qg3g8hFgEIg2gDIAEh/IAsAAQBFAAA+g5IAQgRQAVgwABhAQAAhfg4g7QgqgshHgBIgJAAQg6ACgtAtQgxAwgKBmIgDAiIieAEQAAihBshoQBchaCHADQCeADBdBgQAqArAVA4QAXA8AABMQAACThHBKQgzAzg5AJQAmAMAgATQAcASAYAZQBJBMALB2QABATAAAWIABAcQAACGhSBYIgUAUQhtBki7AAQifAAhthkg");
	this.shape_50.setTransform(145.4,155.0452);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AkTIXQgsgngcgtQghhIAAhUIAAg8IClgNIACArQAEA+AlAuQAPAaAYAXQAyAuBFgCQBZgDA5g5QA3g5ADhzQADgXABgZQAEhmgyg+Qgzg7hBgGIgzgFIAHh7IArAAQBEAAA9g3IAKgKQAPgpABg1QABhbg1g5QgogrhDgCIgCAAQg6gCguAuQguAtgKBgQgCAQAAARIiWAFQAAiXBmhiQBZhUCBAFQCWAFBZBdQApArAUA5QAVA5AABHQAACNhEBJQgwAyg3AJQAyAQAnAfQAOALANAOQBGBKALByQABATgBAUIgBAGQACARAAATQAAB8hOBQIgUATQhuBfi3AAQicAAhthfg");
	this.shape_51.setTransform(144.725,155.3386);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AkOIJQgsglgdgqQgghIAAhTIAAg7IChgRIADAoQAEA5AmAqQAPAdAaAXQAwArBCgDQBWgDA2g3QA3g4AChzIAAgGQABhbgxg2Qgyg3g/gDIgygCIAEhzIATgBIAGhVIAsAAQBDAAA9g0IACgCQAJgiABgqQAChYgyg4Qgkgog8gEIgFAAQg4gDgsAsQgqApgKBbIgCAgIiPAHQAAiOBhhbQBVhPB7AHQCPAGBVBbQAoAsAUA6QASA1AABCQAACIhBBGQguAxg0AJQA8AVArArIAHAHQBDBIAKBuIAAAlIgBAOQADAUAAAWQAAByhLBHIgUASQhtBbi0AAQiaAAhshbg");
	this.shape_52.setTransform(144.025,155.6252);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("AkJH8QgsgjgdgoQgfhHAAhSIAAg6ICbgWIAFAlQAFA0AmAmQAPAfAcAZQAuAoBAgDQBSgFA0g1QA0g3AEhuIAAgSQgDhPgqgwQgvg0g8gEIgugDIADhvIAWgCIAIhZIADgRIArAAQA/AAA5gtQAGgaABgfQAChVgug2Qgggkg0gHQgjAQgcAlQgyBAgGB/IiIAYQAAgmAKghIgvADQAAiFBchUQBRhJB0AIQCJAIBQBZQAnArATA6QAQAyAAA+QAACDg9BEQgrAvgyAKQA+AXAqAvIALALQA2BDAIBhIAAAjIgCAYQAEAWAAAYQAABohGA/IgVARQhtBWixAAQiWAAhshWgAi8k5IBZgGIACgfQAIhRAlgmQAygeA5gLIgKgBQg1gDgoApIgEAEQgZAOgWASQgPAMgOAOQgsAqgQA4g");
	this.shape_53.setTransform(143.35,155.8901);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AkQHTQgrgigeglQgdhHAAhQIAAg6ICXgZIADAUIhvAHIAEAvQAKBwBcBSQBcBRCFAAQCbAABdhRQBRhIAShrQgLgqgfgeQgGgNgIgMQgcgpgtgRQAegDAcgNQAQgNAQgTQgLgRgOgPQgogtg7gXQAugLAqgtQA6hDAAh+QAAg5gOgvIADAFQAQAYAJAdQAfBJAABeQAACKg6BPIgJALQAlA7AHBOQAAAQgBASIgEAgQAHAYgBAcQABBdhDA3IgVAQQhtBSitAAQiUAAhshSgAAEinIAKhjIAEgQIAqAAQA5AAA1gkQADgSAAgUQADhRgrg0QgHgIgHgHQgTgDgSAAQgjAGghAMQAXgaAagPQARgKAUgEQA6gMAjAYQAlAZAIArQACAMAAANQABA0gZAdQgOAQgRANIgPALQgLBDgnApQgmAogrALgAidlcIBCgGIADgeQACgdAHgYQAsghAxgTIgIAKQguBBgGB8IiBAdQABgwARgng");
	this.shape_54.setTransform(143.75,158.9637);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("AkPHNQgsgfgfgkQgbhFAAhQIAAg4ICTgeIAEAXIhkAJIAFAsQALBpBZBOQBZBNCAAAQCVAABahNQBKhAAVheQgLgegZgVQgFgNgHgLQgYgngngQQAegDAbgMQARgQARgUQgPgegWgaQgngrg3gXQAsgLAngsQA4hBAAh4QgBgzgLgrQAIAJAGALQAOAWAGAbQAdBJAABcQAACIg3BPIgEAHQAXAwAFA8IgBAgQgDAVgEAUQAJAZAAAgQAABSg/AvIgUAPQhtBOiqAAQiSAAhqhOgAAxizIgmgKIAMhhIAEgQIArAAQAyAAAvgbIACgTQADhDgeguQgTgEgRgCQgzAIguAVQgcA+gFBhIh5AiQAAg+AjgrIAigDIACgdIAAgDQAHhHAhggQAkgjAuAFQAOABAMADQATgNAVgFQA3gNAhATQAtAbgBA2QAAALgBAKQgEAggSATQgOAPgQAMQgNAJgNAIQgIBMgqAtQgXAYgYANQgKgFgLgDg");
	this.shape_55.setTransform(143.5,158.49);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AkPHHQgsgegfghQgZhFAAhOIAAg3ICNgjIAGAaIAAACIhaAJIAGAqQANBiBVBKQBXBIB6ABQCPgBBYhIQBCg4AXhQQgKgTgTgNQgEgMgFgKQgTglgjgPQAegDAcgMQAQgQAPgVQgPgugegkQglgpg0gXQAqgMAkgpQA0hAAAhzQAAgtgJgnQAPAOALAVQALAVAFAaQAbBIAABaQAACEg0BQIgEAGQANAjADAqIgCAdQgDAbgIAZQAOAaAAAiQAABIg7AnIgUAOQhuBJimAAQiPAAhqhJgAA0jJIgigMIANhfIAFgOIAqAAQAsAAApgUQADgtgNgjIgXgFQg8AJg1AaQALgiAQgbQATgbAWgRQAUgQAXgHQAQgFAOgCQA2AYAmAuIADADQAkAtAOA7QgMgLgQgIQgTgOgWgKIgDADQgOAOgRAMQgSANgTAJIAAACQgEBWguAxQgOANgNALQgQgOgSgGgAg6lWIAegXQAWgPAXgMQgQA1gDBHIhyAmQAAhHA6gpg");
	this.shape_56.setTransform(143.275,158.05);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("Aj3HDQgsgcgfggQgYhEAAhMIAAg3ICIgnIAHAWIADAJIhSALIABAAIAGAnQAPBcBSBFQBTBEB1AAQCJAABVhEQA5gvAZhAQgIgJgMgHQgCgLgEgKQgPgigdgPQAdgCAbgLQAPgPANgTQAEATACAVIgDAcQgFAjgMAeQAVAYAAAlQAAA+g3AeIgVAOQhuBEiiAAQiMAAhqhEgABQjdIgfgOIAPhdIAFgNIAqAAQAlAAAjgOQgBgQgCgOIgCgBQhCAKg6AdQALg1AWgmQAQgYARgQQAVgUAYgJIABgBQAwgRAdAMQAoAQAAApQAAAUgHAOQAhAtAMA7IgHgEQgngfgwgSIgHgCQgSALgTAHIAAAYQgGBSgsAvIgNANQgTgWgVgKgAgJkyIAdgVQARgKARgKQgIApgDAyIhqArQAAg9A2ggg");
	this.shape_57.setTransform(140.65,157.4767);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#000000").s().p("AjzG+QgrgagggeQgWhDAAhLIAAg3ICDgrIAIATQADAJAGAIIhNALIABAAIAGAkQARBXBPBAQBRA/BvAAQCEAABRg/QAtgkAagvIgGgDQgBgKgDgJQgKgggYgOQAcgCAbgKQAKgLAJgNIgDAWQgIAtgTAlQAfATAAAoQABAzg0AWIgVANQhtA/igAAQiJAAhqg/gAAVkOQAOgLAPgJIATgKIAIgwIAHgNIACAAQAKgjAPgcQAMgSAMgPQAOgPAPgLQAKgHAKgFQAugTAbAIQAkALAAAiQABAegUAMIgKAIIAFAFQAnAyALBFQgfgYgjgQQgYgLgXgHIgXAEIgBATQgFBNgrAuIgDADQgTgggYgOIgSgJIAAAHIhjAwQAAgzAygXg");
	this.shape_58.setTransform(139.95,156.9186);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("AjuG5QgrgYghgbQgVhDAAhKIAAg1IB/gvIAIAPQAHANAOAKIhNANIAAAAIAIAhQASBRBNA7QBNA7BqAAQB9AABQg7QAngdAYgnQgHgZgQgMQAXgBAVgGQgIAXgNAVIABAGQACAIAAAKQAjALAAAjQAAApgwAOIgUALQhuA7icAAQiHAAhpg7gAAzjqQAOgKAPgIIARgJIgBgBIgYgQIAThaIAGgLIAZAAQAGgQAHgOIAPgXIAJAMQALARAGAUQAJAfgEAnIgCAVQgJA3geAkQgSgpgYgSIgCAcIhcA1QAAgoAvgPgACpnIQAQgQARgKQArgVAZAEQAiAGAAAbQAAAYgSAIQgOALgRAKIgKAGQghgggrgRg");
	this.shape_59.setTransform(139.275,156.3111);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AjqG1QgqgWgigZQgThCAAhJIAAg0IB5g0IAKAMQAMASAgAIIhZASIAAAAIAJAfQATBKBKA3QBKA3BlAAQB3AABMg3QAjgZAWgfIgCgDIAEAAIgCADQALAMABAYIAAARQAgAFAAAaQAAAegtAGIgUAKQhtA3iZAAQiEAAhpg3gABRjFQAOgJAPgIIANgGIAAABIhWA6QAAgeAsgGgACKjjIgPAHIACgiQgKgRgLgKIgUgSIAUhYIAHgLIAnAAIAKAAIADgFIADAFQAYgCAYgHQgQgLgTgJQATgaAXgPQAngXAXAAQAfABAAAUQAAATgQADQgOALgRAIQgaAPgbAHQAfAWAXAgQAkAzAIBGIgJgGQgVgOgTgJQgzAGgvARQgIASgLAQIgIgXg");
	this.shape_60.setTransform(138.625,155.6745);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AkPGyQgqgUgigXQgShBAAhIIAAgzIB1g4IAKAIQASARAzACQAnACAygXQBAgcAtg5QAWgcAQgjQATAmgHA6QgIBJgkAqQgjAog1ALQgpAJgfgRQgngUgIgjIgEgTIhgAWIABAAIAJAdQAVBEBHAyQBHAyBhAAQBwAABJgyQBIgyAWhPIAFgVQgFhKglg1QgZgkgkgWQAdgOAZghQAkg2AAhaQAAgSgCgRIgRgLQhMAIhBAeIgKAFIgeAPIgDAAIgPABIA4gtIgCgSQgOg1gVgZIgQgUIAVhVIAJgKIAQAAIADAAIgBAAIAUAAQAWAAAVgEQAPgVASgOQAjgYAWgEQAdgEAAANQAAANgQgBQgOAKgQAHQgkASglAHQgIALgHAMQgWgMgZgHQAMAKAJAPQAHANAEAOIAFgOIAKgTQAtAZAfAtQAiAyAHBFIATAOQAkAaAcAjQAHAMgDAZQgBAPgGARQATBFAABRQAAB3gkBSQgMAYgMATQgbAIgbACQAIALgEAZIgDAPQAegCAAARQAAAUgpgDIgUAKQhuAyiUAAQiCAAhpgygAAzifIgWARQAAgPAWgCg");
	this.shape_61.setTransform(142.075,154.9438);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#000000").s().p("AkPGxQgqgTgjgVQgQhAAAhGIAAgzIBwg8IALAFQAUAKAxgDQAmgCAwgZQA8geAsg4QATgZAPgcIAEAGQATAmgIA7QgIBFgjAnQggAmgyAMQgmAKgdgNQglgRgIgeIgEgQIhaAYIABAAIAKAaQAWA+BEAtQBFAuBbAAQBqAABGguQBGgtAXhIIAGgTQgFhGgigzQgWgjghgWQAagOAXggQAgg0AAhVIAAgVIAPgCIAhAcQAgAcAaAkQACALgIAXQgEANgIAQQARBEAABQQAABzggBTQgLAYgMAUQgaAHgaABQACAKgIAXIgGAOQAcgJAAAIQAAAKgmgLIgUAJQhuAtiQAAQh/AAhpgtgAALguIgUgIIAJhJIAYgHQAjgJAhgkIAJgMIgDAgIAggeQADhmAahFQgUgNgXgJQgNgUgWgIIgBAAIAEgMIAJgJIAlAAQAxAAAugSQAXgRAPgGQAagJAAAHQAAAHgNgGQgPAJgQAHIgUAIIgOAMQgdAbgXAyQAkAYAZAnQAiA1AFBIQhIAKg/AbIgdAOIgEgBIgEATQgNA2gWArQgSgfgXgJgAEDisIAAAAg");
	this.shape_62.setTransform(141.895,154.0265);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#000000").s().p("AkXG2QgqgRgkgTQgOg/AAhFIAAgyIBrhAIAMABQAVAEAwgJQAkgFAugbQA6ghArg3QAPgVANgXQAHAJAFAKQAQAlgIA3QgKBAggAnQgeAkguANQgkAKgbgKQgigNgJgZIgFgNIhTAZIABAAIAKAXQAZA4BBApQBBApBXAAQBjAABEgpQBCgpAZhAIAGgRQgEhCgegyQgVghgdgWQAYgOAUggQAcgvABhLQAYgEAYgDIAdAfQAdAeAYAlQgEAJgMAUQgHAMgKAOQAPBFAABOQAABxgdBTIgUArQgZAHgbABIgKATIALAHIgYAQIAIgNIAFgKIgWgNIgUAIQhuApiNAAQh9AAhogpgABPhfIBBhIQAChUARg/QgWgTgbgMIgCgDQgMgbgXgKIgGgDIANgsIAKgIIAlAAQA6AAA3gXQAQgHAPgIIAMAJIgXAOQgSAMgdAcQgbAegUAyIgHAVQAaAWASAfQAjA6AABRIAAAGQg1AJgwAUIgdAMQghgTAAgBgADyh0IAAAAgABXj3QgGg0gMgdIgKgWIADgLQAUADAXAJIAJAEQANAjgHAxQgIA5ggAlQAIgsgBgkg");
	this.shape_63.setTransform(142.475,152.475);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#000000").s().p("ADsHPQAAgKgegdIgUAIQhuAkiJAAQh6AAhogkQgqgPgkgRQgNg/AAhDIAAgyIBmhEIANgCQAXgDAugNQAjgLAsgcQA3gjAqg3QANgQAKgSQALAMAJAVQAMAjgJAzQgJA8geAlQgdAigqANQghALgZgHQgggJgJgUIgGgKIhMAbIAAAAIAMAVQAZAyA/AkQA+AkBRAAQBdAABBgkQBAgkAbg6IAGgPQgEg+gagvQgSghgagVQAUgPATgeQATgjAFgzQghAHggALIgdALQgdgbAAgMIA5hNQABhAAKg0QgagfgkgSIgEgNQgJgbgUgJQgIgFgGgBIAZhMIAKgHIAlAAQA5AAA2gWQARgFAOgHQALAPAAAEQAAAGgUAUQgQAPgaAeQgYAggSAxQgHAYgFAaQAOAQALAUQAgA3AABMQAAATgCARQAogJAqgEIAaAhQAaAgAVAlQgKAJgQASIgWAYQAOBEAABMQAABtgaBUQgIAXgKAUQgZAGgaACIgZAaIgLALQAWgXAAgJg");
	this.shape_64.setTransform(143.025,152.05);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#000000").s().p("ADaHWQAAgVgagkIgUAHQhuAfiGAAQh3AAhogfQgqgNgkgPQgMg/AAhCIAAgwIBihJIANgGIBFgcQAigOAqgeQAzglAqg2IARgZIADAEQAPAMAKAfQAJAggJAvQgKA4gcAjQgbAggnAPQgeAMgWgEQgfgGgJgOIgFgHIhHAcIABAAIAMASQAbArA8AgQA7AgBMAAQBWAAA/ggQA8ggAdgyIAHgNQgDg7gYgsQgPgfgXgWQASgPAQgcQALgWAGgbIgaAHIgeAKQgZgkAAgWIAxhSQACgoAEgkQgdgzgvgaIgDgCQgBgLgEgLQgGgZgQgKQgGgFgEgBIgBgIIgDgaIAdhNIALgGIAjAAQA4AAA2gSIAggLQAKASAAAKQgBANgSAZIgkA0QgVAhgQAxQgKAogFAwIAEAJQAbA1AABHQAAAkgFAeQA5gQA+gEIAXAjQAWAhATAoQgPAHgVAQIgbAVQANBDAABKQAABrgXBUIgQAsQgZAFgZABQgOAHgVAQIgNAKQATgeAAgSg");
	this.shape_65.setTransform(143.6,152.25);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#000000").s().p("ADIHdQAAgfgXgtIgUAGQhuAciDAAQh0AAhngcQgqgLglgMQgKg+AAhBIAAgvIBdhOIAOgKIBFgnQAhgSAnggQAxgmAog2QARgYAPgbIgKAqIAJALQALANAHAdQAGAfgKArQgLA0gbAgQgZAggiAPQgbAMgWgBQgbgBgKgKIgGgEIhAAdIABAAIANAQQAdAlA4AbQA5AcBHAAQBPAAA8gcQA6gaAegsIAIgLQgDg2gUgsQgNgcgUgWQAPgQAOgaIAFgNIgNAEQgWgrABggIAqhXQgFgdgMgZQgZg3grgdIgOgKQAAgPgCgNQgFgXgMgLQgIgKgGAAIADgnIAAgbIAehLIAMgGIAiAAQA4AAA2gQIAfgJQAIAXAAAQQAAAUgQAeIgeA5QgSAjgOAyQgQBGgCBbQAHAdgBAiQABA3gPAoIAQgFQBFgRBMgFIATAlQAUAkAPAoQgUAHgaAOIgeARQAKBDAABKQAABngTBUIgOAsQgYAFgZAAQgUAGgZAOIgQAIQARgkAAgbg");
	this.shape_66.setTransform(144.2,152.45);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#000000").s().p("AC1HlQAAgrgTg0IgUAEQhtAXiAAAQhyAAhmgXQgqgJglgKQgIg9AAhAIAAguIBmhfQAbgWApgdQAhgXAkghQAvgoAmg3QAqg8AdhKQARgsALgnQAGAAAPAGQANAFAPAMQgBARgFAUQgLAqgYAeQgVAbgWANIgPAJIgPAzIAGALQAIAPAEAbQADAdgLAoQgLAugYAgQgXAdgfAQQgZANgTACQgZACgLgEIgGgCIg6AgIABAAIAOANQAeAfA1AXQA3AWBBAAQBKAAA4gWQA3gXAggkIAJgJQgDgzgQgpQgMgcgQgVQANgQALgZQAGgQAEgRQAFAWAJAbIAdgHQBFgPBKgFIAQApQAQAmANAqQgaAFgeALIgjAPQAJBCAABIQAABkgRBVIgLAsQgYADgZABQgYAFgfAMIgRAHQANgsAAgigACbi3QgVg1gkgfQgNgMgLgIQACgQgCgNQgCgWgJgMIgFgJIAAgCQgHgHABAEQADABADAEIgBAOIgeAeIAJgiIAPhVIAEgdIAghJIAMgFIAiAAQA3AAA1gNIAfgIQAHAcAAAUQAAAcgNAjQgKAbgQAkQgOAlgMAxQgNBHgBBXIgZBAQgBg5gTgugABKkfIAAAAg");
	this.shape_67.setTransform(144.775,152.675);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#000000").s().p("ACjHsQAAg1gPg9IgUAEQhuASh7AAQhwAAhmgSQgpgHgngJQgGg8AAg+IAAguIBihmQAdgdAogiQAegbAjgiQArgrAlg2QApg8AfhIQAbg/ARg4IAXhWIAIgeIAhhIIANgEIAiAAQA2AAA0gKIAggGQAGAfgBAbQAAAigKAoQgIAfgNAmQgMAngJAxQgKBHgCBVIgcBhQAAA0APA9IAdgGQBEgMBJgDIAMArQANAoALArQgfAEgjAJIgnAMQAGBBABBGQAABigOBVIgJAsQgYADgYABQgeADgiAKIgVAFQALgyAAgrgAA3j4QgMAmgVAcQgUAZgTAOIgOAJIgPAvIADAMQAEAPABAZQAAAdgLAjQgMApgXAeQgUAcgbARQgWAOgSAEQgXAHgKABIgHAAIg0AiIABAAIAPAKQAgAZAyASQAzASA8AAQBEAAA2gSQA0gSAigdIAJgHQgDgvgMgnQgKgagNgVQALgRAJgYQANgogBg2QAAg4gPgtQgRgygdghQgTgXgOgOQgDARgFAUgAA3loIAEAOIgYAgQABAGATAQIAIAHQACgNAAgMQAAgUgFgNIgBgDIAFgGIABgOIgEAAQgFAAgBAGg");
	this.shape_68.setTransform(145.35,152.875);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#000000").s().p("ACRHzQAAg/gLhFIgUADQhuAOh4AAQhtAAhmgOIhQgMQgFg8AAg8IAAgtIBehvQAegjAngnQAdgdAhgmQAogtAkg2QAog8AghFQAdg8AUg4IAghXIALggIAjhGIANgCIAiAAQA1AAA0gIIAfgFQAEAlAAAfQAAAqgHAtQgGAjgKAnQgJApgHAxQgHBIgBBRIgWBmQAAA/ALBFIAdgDQBEgKBIgDIAJAuQAKAqAIAsQglADgnAHIgsAJQAFBBAABEQAABfgKBVIgHAtQgXACgYAAQgkADgnAHIgWAEQAIg5AAg0gAApj2QgLAhgUAbQgQAWgSAPIgMAKIgQArIAAANQAAAPgCAXQgDAbgLAgQgNAlgVAdQgSAZgYASQgTAOgPAIIghAQIgHAEIgsAjIABAAIAPAHQAiATAvAOQAwANA3AAQA+AAAzgNQAxgOAjgVIAJgGQgBgqgKgmQgHgYgKgWQAIgQAHgXQAKgmAAgxQAAgzgMgrQgNgvgVgjIgfgzIgKgRQgDAXgKAcgAA5lkQgBAGAAAOIABAEIgIAOQAAAJAFAMIABgGQACgRAAgMIANgaIABgMQgJADgFALg");
	this.shape_69.setTransform(145.925,153.05);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#000000").s().p("AB+H6QABhJgIhNIgUACQhtAJh2gBQhqABhlgJIhRgJQgDg6AAg8IAAgsIBbh2QAegqAlgsQAdgiAegnQAmgwAjg1QAmg8AihBQAeg7AZg2IAnhZIAzhlIAPgCIAgAAQA1AAAzgFIAfgEQAEAqAAAlQAAAwgGAzQgEAmgGAqQgGArgEAwQgGBIgBBPIgOBrQAABJAHBNIAegCQBEgHBGgBIAGAwIAMBZQgrACgrAFIgxAGQAEBAgBBDQABBbgHBWIgFAsIguACQgqACgrAFIgZACQAGg/gBg9gAA8lgQgEAJgDAOIgHAgQgHAYgLAcQgMAegRAYQgPAVgPAQIgKAKIgRAmIgDAOIgJAlQgGAagMAcQgNAggTAbQgRAYgTASQgQAQgOAKQgSAOgNALIgtAsIABAAIAQAEQAjANAtAJQAtAKAyAAQA4AAAvgKQAugJAlgPIAKgDQAAgngIgjQgEgXgHgVQAGgRAEgVQAHgmAAgqQAAgugIgpQgIgsgOglIgWg7QgJgdgBgZIAPgoIAAgNQgKAKgHAOg");
	this.shape_70.setTransform(146.5,153.25);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#000000").s().p("ABsIBQAAhTgDhWIgUABQhtAEhyAAQhoAAhlgEIhRgEQgCg6AAg6IAAgsIBWh+IBFhhIA3hPQAjgyAhg0QAmg8Ajg/QAgg4Adg2IAvhbIA4hkIAvgBQAzAAAzgDIAggBIABBYQAAA3gCA3IgFBXIgGBcQgCBJgBBMIgHBvQAABUAEBXIAdgCQBEgDBFgBIADAzIAGBcIhgADIg2ADQACBAAABBQAABZgDBWIgDAtIgtAAIhfAEIgbABQAChHAAhFgAA+ldIgNAbIgNAgQgJAWgMAYQgNAagOAXIgaAjIgJALIgXAwIgPAlIgWAwQgOAbgRAZQgOAWgRAUIgYAdIgdAiIgnAwIABAAIAQADQAlAGApAEQArAFAsAAQAyAAAtgFQArgEAngHIAKgCQAAgjgEghQgCgWgDgVIAFglQADgjAAgmQAAgpgEgmQgEgqgHgmQgHgjgEgfQgFgkAAgiIAHgrIABgLQgMAPgKARg");
	this.shape_71.setTransform(147.075,153.475);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#000000").s().p("ABaKkIAAlYIoKAAIAAicIIKtTICzAAIAANbICkAAIAACUIikAAIAAFYgAkFC4IFfAAIAAo6g");
	this.shape_72.setTransform(147.65,153.675);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#000000").s().p("ABrHuQAAhMgChPIhpAHQhfAEhiAAQhbAAhagEIgygDQgChPgBhQIAAgBIBAhcIBNhuIAuhAQAdgqAcgrQAzhSAwhWIBXieIAhhBQAYgsAZgrIAFABIA2ADIBWAAIASgBIAAAOIACFjIAcGSIAAAZIBBAFIBVAAIgKCOIhjABIhAAEIAAB2IgBAfIAKCPIADAsQg8AAg9AEIgqACQADhNAAhMgAA3lkIhQCZIgHANIgMAgIgJAPQgJAQgHASIgLAbIghBFQgSAlgXAjQgMASgOARIgVAXIggAnIgeAjQAnAJAqADQAmAFAoAAQArAAAogFQA6gFA1gMIARgDQgBgngEgkQgEglgGghIgKg2IABgNIABhXIAWh6IAAgqIgVhzg");
	this.shape_73.setTransform(147.275,153.35);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#000000").s().p("AB7HkQAAhDgEhGQgzAHg1AFQhfAJhlAAQhfAAhagJIgygFQgEhQgChTIAAgBIBFhYIBNhgIAxg7QAhgoAcgsQA1hSAthaIBRikIAbg/QATgrAVgmIAEAAQAXAFAaABIBMAAIARgCIAAANIADE4IA4GAIAAAbIA/AJIBLAAIgUCIIhXAAIgOABIg9AJIgBB5IgBAfIASCFIAGAqQg0ABg3AHIgmAFQAFhFAAhBgAArlvIhOCvIgHAOIgFAeQgEAIgCAFQgFAMgDAQIgGAcQgLAigRAsQgSAtgZAkQgOAUgRAQQgOAMgMAIQgTARgPALIgkAiIAAAAQAnARAsAIQApAJAtAAQAwgBArgIQA9gMAzgXIAQgGQgBgrgIgnQgIgogNggQgKgcgIgTIAAgOIAChhIAsh1IAAgvIgphtg");
	this.shape_74.setTransform(146.925,153.05);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#000000").s().p("ACMHZQAAg4gFg+QgzAKg2AHQhfAOhoAAQhiAAhagNIgygIQgHhQgDhXIAAAAIBLhUQAjgkAqgvQAZgYAbgdQAjgmAeguQA2hRArhgQAqhcAfhMIAWg+QAOgpAQgiIAFABQAUAGAXADIBCAAIARgEIAAAMIAEEMIBUFvIAAAbIA8AOIBAAAIgdCBIhZAAIgNAEIg7AMIgCB8IgBAgIAcB7IAJAoQgtACgxAKIgiAHQAHg9AAg3gAAfl5IhLDEIgHAQIABAdQgDAFABAEQgCAHACARQAAALgBASQgHAjgRAxQgRA1gcAnQgQAVgUAQQgRALgMAGQgWAOgOACIgsAhIAAABQAmAZAwAMQArANAyAAQA1AAAtgOQBCgSAxghIAPgJQgCgwgLgpQgNgrgUgfQgOgagNgPIABgPIADhrIBBhwIAAgzIg9hpg");
	this.shape_75.setTransform(146.55,152.7);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#000000").s().p("ACdHNQAAgugIg1QgyANg2AKQhgAShrABQhjAAhcgRQgZgFgYgGQgKhRgDhZIBPhQQAjgcAqgqQAagUAegdQAlgkAfgtQA4hSAphlQAnhgAchNIAPg+QAJgnANgcIADABQARAIAVAEIA3AAIAQgEIAAAJIAHDhIBwFeIAAAbIA5ASIA2AAIgoB8IhbAAIgMAEIg4ASIgDB+IgCAgQARAwAUBBIAMAmQglADgrANIgfAKQALg2AAgtgAkMDUIAAAAQAlAiAyAQQAtARA4ABQA7gBAwgRQBFgYAugtIAOgLQgDg3gPgrQgRgtgZgeQgUgZgRgJIACgRIADh1IBYhqIAAg4IhRhjIg0AhIhJDYIgIASIAKAcQgDAEADAAIAIAVQAEAKAAATQgDAlgQA4QgQA9geApQgSAWgZAPQgSALgPADQgXALgPgFg");
	this.shape_76.setTransform(146.2,152.4);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#000000").s().p("ACuHDQAAglgKgtQgxARg3AMQhgAXhuAAQhnAAhbgVQgagGgYgHQgMhRgEhdIAAAAIBUhMQAigTAsgkQAagSAggbQApgjAggsQAbgoAYgtIAIANQgBABAAAAQAAAAABABQAAAAABgBQABAAABAAQAFAAAKAPQAHALADAUQAAAmgOBAQgQBDghArQgUAZgcANQgVALgQABQgZAGgPgLIg4AdIAAABQAkAqA1AUQAwAWA9AAQBAAAAzgXQBJgdArg4IAOgPQgEg7gSgtQgVgxghgcQgYgXgVgFQAAgJABgJIAFh+IBthmIAAg8IhlhfIgWAMIAIg0QAEglAIgYIADABQAOAKAUAFIAsAAIAQgGIAAAIIAIC2ICMFMIAAAcIA2AXIAsAAIgxB2IheAAIgLAEIg2AXIgECBQgBAQAAARQAVApAYA9QAIASAHATQgeAEglAQIgbAMQAOguAAgig");
	this.shape_77.setTransform(145.825,152.075);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#000000").s().p("AC+G4QAAgbgMgkQgwAUg2APQhiAbhwAAQhqAAhcgaQgZgGgZgJQgOhSgFhgIAAAAIBahIQAggKAtgfQAcgOAhgaQAsghAhgtQAfgrAZgzQAGADAHAHQAJAKAGAVQAEApgOBGQgPBKgkAtQgVAbggANQgYAKgSgCQgbADgPgTIg+AcIAAABQAkAyA3AZQAzAZBCAAQBEAAA3gbQBNgjAphCIAHgLIABgSIADgCQgFg5gUgrQgZgzgngaQgegXgZABQAAgKACgKQAEg+AChKICChfICHD+IAAAcIAzAbIAiAAIg8BvIhfAAIgLAGIgwAYIABAMIgFAIIgEByQgCASAAAQQAaAjAdA5QAKARAIATQgXAEgfAUIgXAOQAQgmAAgYgAA9m1IgFACIgBgMQAAgjAEgTIADABQAKAMASAGIAiAAIAPgHIAAAGIAIBtg");
	this.shape_78.setTransform(145.475,151.775);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#000000").s().p("ADPGtQAAgQgOgdQgwAYg2ARQhiAghzAAQhtAAhdgeQgZgIgYgKQgRhTgFhiIBehEQAggBAtgaQAdgLAkgZQAugeAjgvQAkgwAbg+QAKAKAGAUQAHAqgMBNQgOBSgnAvQgXAcgjAMQgaAKgUgEQgdgBgPgaIhFAaIAAABQAjA7A5AdQA3AeBGAAQBKAAA6ggQA4gdAkguIgCAiQgCARAAARQAeAbAiA3QALAQAKARQgQAGgZAWIgTARQATgeAAgOgACvA8Qgeg2gtgYQgigVgeAFQAAgKACgLQAFhCAChQICGhPICSDdIAAAdIAwAfIAXAAIhFBpIhhAAIgLAHIgVANQgIgkgPgegAA4m+QgDgRABgJIACACQAHANAQAHIAXAAIAPgIIABAEIAFAwg");
	this.shape_79.setTransform(145.125,151.425);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#000000").s().p("Ak7GqQgagKgYgLQgUhUgFhlIAAAAIBjhAQAfAIAugVQAegIAngXQAxgdAjgvQAog0AchHIAHAQQAMArgNBUQgNBZgpAyQgYAdgnAMQgdAJgVgHQgfgEgQgiIhLAZIAAABQAjBDA8AiQA5AhBLAAQBPAAA9gkQAjgTAbgbIgFgDQAAgSADgSQADhEAChFIAtgjQgGgQgIgOQghg4g1gXQgngVgiALQABgLACgMQAEgyACg5IANg2QARhHAGgzQgCglgIgWIgOgpIABACQAEAPAOAIIAOAAIANgJIABACIANA2IDgEYIAAAeIAtAkIANAAIhPBiIhkAAIgKAIIgBABQARArAFA2IgMAZQgVAzglAmQAgAUAkAwQANAPALARQgHAFgOAUQgBgHgPgTQgvAag3AUQhjAkh2AAQhvAAhdghgADaGaIAGgHIAAAAQAAADgWAXIAQgTg");
	this.shape_80.setTransform(144.75,152.625);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#000000").s().p("AkyGfQgagKgYgNQgWhUgHhoIAAgBIBpg7QAeAQAvgPQAfgEAogWQA0gbAlgwQAog0AbhHIAHgDIgDgJIAAAAQAMgjAKgmQARhEAIg1QAGgqACghQgFgmgLgUIgEgIIALgIIAAAAIAPALID8EHIAAAeIAqApIADAAIhZBbIhkAAIACAEQAiA3AGBPIgKAbQgRAzgfAmQgZgUgXgIQAAgSADgTQAEhFAChHIAsgoIAJgJIACAAQglg4g5gVQgmgRgiAKQALAtgLBSQgMBggrA0QgbAfgqALQggAJgWgKQghgIgPgpIhSAXIAAACQAiBLA+AmQA8AmBQAAQBUAABBgpQArgaAegmQARAOARATQAOAOANAQQgBAHgNAdIgDAHIgCgBQguAeg3AWQhlAph3AAQhzAAhdgngADhFqIAJAGQgGACgLAHIAIgPgAA6moQgMgJgBgRIgBgDQAHAFAMAWIgDACg");
	this.shape_81.setTransform(144.375,154.65);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#000000").s().p("AkuHBQgagMgYgOQgYhVgHhrIBtg4QAdAZAwgKQAhgBApgUQA3gZAmgxQAug7AchUQAKAugJBPQgLBnguA2QgdAhgtAKQgiAIgZgMQgjgMgPgvIhYAVIAAACQAhBTBBAqQA/AqBVAAQBZAABEgtQA0giAhgyQgxgtgqgGQAAgSADgTQAEhHADhIIApgsIAJgJIAMAAQgkgpgygPQgZgJgYABIAMgtQAVhkAEhDIhCAWQgDBbgGBLQgFgEgGgCQgggLgWATIgTARIg1gTQAFgQACgNIBAlVIBagXIDLBFIAABUIg8AUIClCRIAAAfIAnAtIgIAAIhjBXIhbAAQALALAKAPQAmA5AHBVIgJAfQgOAvgYAmQAPANAPAPQAGAIgHAgQgCALgFANQAagHAAARQAAAOgUgDQgtAhg3AZQhlAth7AAQh1AAhegqg");
	this.shape_82.setTransform(144.425,152.375);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#000000").s().p("AkrHKQgagNgYgQQgahVgIhuIAAAAIByg1QAcAjAygGQAhAEAsgTQA5gYAngwQAwg+AchZQAHArgHBFQgKBvgxA5QgfAigxAJQgkAHgagOQglgPgPg3IhfAUIAAACQAgBbBEAvQBBAuBbAAQBeAABHgyQA+grAihDIAAgBQgQgPgRgMQg2gqgvACQAAgSAEgTQAFhJADhKIAngvIAIgLIANAAQgfgXgmgKQgMgEgMgBIACgNQAaiDgGhKIgBgDIhSAYQgEBggHBPQgggHgYAVQgTAQgEAFIg8gSQAFgRACgOIA+lqIBhgVIDfBAIAABZIhEATIClB7IAAAgIAlAyIgSAAIhtBQIhcAAQAbAVAWAeQApA7AIBaIgIAiQgKApgSAjQANAJgBAiQAAAMgDAPQAdABAAAbQAAAYgWAEQgtAlg3AbQhmAzh9gBQh4ABhfgvg");
	this.shape_83.setTransform(144.575,152.5);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#000000").s().p("AknG0QgbgOgYgSQgdhWgIhxIB3gwQASAcAbAKIhOAOIAAACQAgBkBFAyQBFAzBfAAQBlAABJg2QBDgxAihOQgGgegTgJQgRgOgTgLQg6gngzAJQAAgTAEgTQAFhKADhKIAkg1IAHgLQgRgHgTgEIgDgBQAUh6gKhFQgIgVgJgOQgIgNgKgIQgfgXgTAIIgBADQgIAYAGALIgcAAIALgNIACgFIASh2IFQDSIAAAgIAiA3IgdAAIh3BKIhrAAIgBABQA3AXAmA0QAtA8AIBgIgHAkQgJAqgPAjIABAJQACANgCAQQAgAJAAAlQAAAigYANQgsAog3AeQhmA2iBAAQh6AAhfgyg");
	this.shape_84.setTransform(144.75,155.775);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#000000").s().p("AkkG/QgbgPgXgTQgghWgJh1IB9gsQALAXAQANIhJAMIAAACQAfBtBIA2QBHA3BlAAQBpAABNg7QBFg0AihTQAfAQAAAuQAAAsgZAWQgrArg4AgQhmA7iEAAQh9AAhgg3gAiMEhQghgSgRgxIAJACQAjAJAwgQQA/gTApgzQAegkAWgxIAIiNIAEgHIAcgwIgJgBQglgJghAJIgHgBQgUgFgSAEIACgGQAHhQAEhgIAJAAQgEgLAIgUIgMACIgBAdIgeAAIALgOIABgIIAVigIFrDBIAAAgIAfA8IgnAAIiBBDIhuAAIAAABIgBAQQBKATAyBAQAwBAAIBkQgCATgDAVQgJAugPAnIgDgCQAAgRgEgOQgLgqgcgKQgSgNgVgLQgvgagrACQgOBigvAzQghAmg4AIQgLACgJAAQgdAAgWgPg");
	this.shape_85.setTransform(144.9,155.65);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#000000").s().p("AkhHLQgbgQgXgVQgihXgKh3IAAAAICCgoQAIATAKAOIhNAKIAAACQAgB1BKA7QBKA7BqAAQBuAABQhAQBRhAAghrQAWAYAAAsQAAA2gcAeQgqAvg4AiQhnBAiGAAQiBAAhgg7gAEGDQQgCgTgGgPQgQgugkgKQgUgNgWgKQgggPgegDQgLgBgLABQgXABgVAIQAAgUAFgUQAFhLAEhOIAGgLQALAIAIAMQAXAkAEBDQAHgdAEgiQAHgsACglQgQgFgRgDIgRgCQgngEgkAQQgSAAgQAHQABgKADgJQAGhBAEhKIgrAAIAKgQIACgJIAXjMIGHCvIAAAiIAcA/IgyAAIiKA+IhNAAIgBAsQBFAVAwA8QA0BBAKBqQgBAUgEAWQgGAjgJAfQgGgIgJgFg");
	this.shape_86.setTransform(145.05,155.525);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#000000").s().p("AkeHWQgbgRgXgWQgkhYgLh6ICHgkQAFAQAHAOIhTAJIAAACQAfB+BNA+QBNBABvAAQBzAABThEQBbhLAdiCQgJgRgPgMQgEgUgIgQQgXgwgrgMQgVgMgYgIQgSgIgSgDIgGgBQgxgJgtAWQAAgVAFgUQAGhLAEhPIAAgCIAKgYQgwAFgsAgQAAgQAFgRQAFgxADg1Ig3AAIALgRIABgLIAYj3IGjCeIAAAiIAaBEIg9AAIiUA4Ig0AAQAFAeAAAnQBDAWAvA6QA4BEAKBuQgBAWgDAYQgDAZgGAYQAQAdAAAqQAABAgeAmQgqAzg4AkQhoBFiJAAQiDAAhhhAg");
	this.shape_87.setTransform(145.225,155.425);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#000000").s().p("AkbHiQgagTgXgXQgnhZgMh9ICMgfIAJAaIhcAIIAAACQAeCGBQBDQBPBEB0AAQB5AABWhJQBkhUAZiVQgKgdgVgUQgGgVgKgRQgdg0gygMQgXgMgZgHIgIgDIgFAeIgCgfQgGhMgcgnQgcgjgngFIgPAAIACgeIAAgBQgnAKglAdQAAgSAGgRIAGhCIhDAAIAKgSIABgNIAakiIG/CNIAAAiIAXBJIhHAAIieAyIguAAIAJAOQAOAgAEAwQBCAXAvA3QA8BHALB0QgBAXgDAZIgFAmQALAdAAAoQAABKggAvQgoA2g5AmQhoBJiMAAQiGABhihEg");
	this.shape_88.setTransform(145.375,155.3);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#000000").s().p("AkXHtQgbgTgXgZQgqhagMh/IAAAAICRgcIAHAWIhmAIIAAACQAdCPBTBHQBSBIB5AAQB+AABZhNQBrhdAViqQAJAfAAAlQAABVgiA2QgoA5g5AqQhpBNiPAAQiJAAhhhIgAFFC2QgKgogagbQgIgXgLgSQgjg3g6gNQgPgGgQgFQAHhjgOhAQBEAXAxA5QA/BJAMB4QAAAZgDAbIgDAZIAAAAgACBgKIARAFIgBATQgDAhgFAdQgBgxgHglgAgWgfIAHhlQASgDAVACQAqADAfAlQAWAeAKA1IgDgBQhTgWhHArQAAgUAGgVgACSgFIAAAAgAhLipIADgdIhNAAIAJgTIABgPIAclMIHbB6IAAAkIAUBNIhSAAIinArIh2AAIgDAMQAUgCAXAGQAmAJAbArQALAVAGAdQgfgKgigDQgtgFgpAPQgjAMghAbQAAgTAFgSg");
	this.shape_89.setTransform(145.525,155.175);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#000000").s().p("AkUH5QgbgVgXgbQgshagMiBICVgZIAFATIhvAIIAAABQAbCXBWBMQBVBMB+AAQCDAABbhSQBzhlARi7QAGAdAAAjQAABegkA+QgnA9g5AtQhpBRiSAAQiMAAhihMgAFTCuQgLg3gfgjQgJgYgNgTQgpg6hCgNIgJgEQAAAigCAnQgDAggFAeQABhagTg2IAcAJQgBhdgWg2QBKAXA1A7QBDBMAMB+QABAagDAdIgBAQIAAAAgAgqg5IAFhCQAegMAiACQAuAEAgAmQAQATAKAdIgRgDQhXgThLAzQgBgVAHgWgAhaioIhWAAIAJgUQACgJAAgIIAcl3IH3BpIAAAkIASBRIhcAAIiyAmIh2AAIgFASIgQA+QAjgTAuAJQAqAJAdAqIAJASQgfgJgjgCQg2gFgxAWQgfAOgdAYQAAgQADgPg");
	this.shape_90.setTransform(145.7,155.05);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#000000").s().p("AkRIEQgbgVgWgcQgvhbgNiFICbgUIADAPIh6AGIAAADQAbCfBYBQQBYBQCDAAQCIAABfhWQB4huAOjLQgKhFgkgtQgLgZgQgVQgtg6hFgQQAHA4gFBKQgCAfgEAdQACiMgqg+IgSgDQhdgQhQA6QAAgVAHgWIACgbIAGhEQgSAKgSANQgGAKgDAHIhnAAIAIgVQACgKAAgIIAfmjIISBYIAAAlIAOBWIhlAAIi8AeIh5AAIgDATIgTBUIgEAyQAvglA8AKQAjAFAbAbQBbATA/BFQBHBOANCDQABAcgCAeIAAAJQAEAbAAAfQAABogmBHQgmBAg5AvQhrBWiUAAQiPAAhjhRg");
	this.shape_91.setTransform(145.825,154.925);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#000000").s().p("AkOIQQgbgXgWgeQgxhbgOiIIAAAAICggQIACAMIiFAFIAAADQAbCnBaBUQBaBVCJAAQCNAABihbQB+h1AJjeQADAaAAAcQAABygoBQQglBCg5AyQhrBbiYAAQiRAAhkhVgAE7AWQgMgagSgVQgyg9hIgRQAWBHgFB3QgBAggEAcIAAgEQADing3g/QgTgVgXgLQhagIhQA+QAAgMACgLIAFgVIAEgzQgdAigIASIhyAAIAIgWQACgLAAgJIAhnOIIuBGIAAAmIALBaIhwAAIjFAZIh7AAIgDAUIgRBYIgHBnQBCgpBJAEQCCAFBUBbQBLBQANCIQACAdgCAgQgJhSgpg2g");
	this.shape_92.setTransform(145.975,154.8);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#000000").s().p("AkKIjQgcgYgWgfQgzhcgPiLIClgMIABAJIiRAEIAAADQAbCwBcBYQBeBYCNAAQCTAABlhfQCBh7AHjpIABgJQgJhggtg9QgPgcgTgXQg8hEhWgQIgGgCIAEAFQA3BHgFC0QgBAegDAbIAAgPQADiug8hBQgogrg1gCQhQgCg8A7QgoAogNATIiHgEQAIgcABgVIAso6IClgFIGoAPIAAAzIAWACIAAAmIAJBfIh7AAIjPASIh9AAIgCAVIgOBdQgFBCgGBBQBLgzBTADQCIAEBZBeQBOBTAOCNQACAaAAAcQACAYAAAaQAAB8gqBYQgkBGg7A0QhrBfibAAQiUAAhjhZg");
	this.shape_93.setTransform(146.15,153.925);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#000000").s().p("AkLInQgcgZgWghQg2hcgPiOICqgIIAAAFQAQBsAtA1QAIAJAJAIQAtAoBCgDQBXgDA0g2QBGhIAOiUQADgcAAgfQAEi4g9hHQgogug4gDQhPgDg8A2IgGAGQgoArgMAVIiHAAIAHgYQACgNAAgLIAkojIJmAjIAGCKIiFAAIjaAMIh/AAIgBAWIgMBhQgFBSgIBQQBTg/BdACQCPADBdBgQBSBVAPCSQACAZAAAaQABAVAAAWQAACGgsBgQgjBKg7A2QhsBkidAAQiXAAhkhdg");
	this.shape_94.setTransform(146.725,154.575);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#000000").s().p("AkOIyQgbgZgXgjQg4hdgQiRICvgDIAAACQAPB4AwA7QAJAMAKAJQAtAsBDAAQBagBA1g1QBLhMAIioIACgyQACi9hChHQgrgug7gBQhUgChAA7IgGAGQgsAtgOAXIiRAAIAGgaQACgOAAgMIAlpOIKDARIADCQIn0AGIAAAWIgKBmQgGBbgKBaIgEAPQBchOBqABQCVABBiBkQBVBWAQCYIADAsIABAnQAACQguBpQgjBNg6A4QhtBpigAAQiaAAhlhig");
	this.shape_95.setTransform(147.475,154.45);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#000000").s().p("AkQI+QhmhlgXjLIC0AAQAPCUA/A/QAuAvBHAAQBdAAA2g3QBWhWAAjLQAAjDhGhGQgvgvg+AAQhdAAhHBHQguAugRAXIicAAQAJgegBgYIAnp5IKfAAIAACVIoKAAIAAAXQgICVgQCMQgHAYgBAXQBmheB1AAQCbAABmBmQBtBtAADSQABEKiNCNQhtBtikAAQicAAhlhmg");
	this.shape_96.setTransform(148.2,154.325);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},10).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_45}]},1).to({state:[{t:this.shape_46}]},1).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_48}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_52}]},1).to({state:[{t:this.shape_53}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_56}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_58}]},1).to({state:[{t:this.shape_59}]},1).to({state:[{t:this.shape_60}]},1).to({state:[{t:this.shape_61}]},1).to({state:[{t:this.shape_62}]},1).to({state:[{t:this.shape_63}]},1).to({state:[{t:this.shape_64}]},1).to({state:[{t:this.shape_65}]},1).to({state:[{t:this.shape_66}]},1).to({state:[{t:this.shape_67}]},1).to({state:[{t:this.shape_68}]},1).to({state:[{t:this.shape_69}]},1).to({state:[{t:this.shape_70}]},1).to({state:[{t:this.shape_71}]},1).to({state:[{t:this.shape_72}]},1).to({state:[{t:this.shape_73}]},1).to({state:[{t:this.shape_74}]},1).to({state:[{t:this.shape_75}]},1).to({state:[{t:this.shape_76}]},1).to({state:[{t:this.shape_77}]},1).to({state:[{t:this.shape_78}]},1).to({state:[{t:this.shape_79}]},1).to({state:[{t:this.shape_80}]},1).to({state:[{t:this.shape_81}]},1).to({state:[{t:this.shape_82}]},1).to({state:[{t:this.shape_83}]},1).to({state:[{t:this.shape_84}]},1).to({state:[{t:this.shape_85}]},1).to({state:[{t:this.shape_86}]},1).to({state:[{t:this.shape_87}]},1).to({state:[{t:this.shape_88}]},1).to({state:[{t:this.shape_89}]},1).to({state:[{t:this.shape_90}]},1).to({state:[{t:this.shape_91}]},1).to({state:[{t:this.shape_92}]},1).to({state:[{t:this.shape_93}]},1).to({state:[{t:this.shape_94}]},1).to({state:[{t:this.shape_95}]},1).to({state:[{t:this.shape_96}]},1).to({state:[{t:this.shape_96}]},13).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(252.3,236,-61.30000000000001,-13.199999999999989);
// library properties:
lib.properties = {
	id: '100A7DCE488A7F42A66966B32369E51D',
	width: 300,
	height: 300,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['100A7DCE488A7F42A66966B32369E51D'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;